# Use postgres/example user/password credentials
version: '3.8'

services:
  web:
    build: .
    ports: 
      - "81:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports: 
      - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql
    restart: unless-stopped  

volumes:
  db_data:
