# Use postgres/example user/password credentials
version: '3.8'

services:
  pythonflask:
    image: pythonapp

  
  nginx:
    image: nginx
    ports: 
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf 
  